from .bass import Bass
from .bassfx import BassFX
from .vocals import Vocals
from .vocalsfx import VocalsFX
from .console import Console
from .inputs import Inputs
from .outputs import Outputs
from .synths import Synths
from .samples import Samples
